---
- name: 'reconfigure debian pam'
  command: '/usr/sbin/pam-auth-update --package --enable  mkhomedir'
  environment:
    DEBIAN_FRONTEND: 'noninteractive'
  when: ansible_os_family == "Debian"

- name: 'reconfigure redhat pam'
  command: "/usr/sbin/authconfig \
    --enablesssd --enablerfc2307bis \
    --enablesssdauth --disableforcelegacy \
    --enablelocauthorize --enablemkhomedir \
    --enablepamaccess --updateall"
  when: ansible_os_family == "RedHat"

- name: 'restart sssd'
  systemd:
    name: 'sssd'
    state: 'restarted'

- name: 'clear sssd cache'
  command: '/usr/sbin/sss_cache -E'
  ignore_errors: true
